import { useMemo, useState } from 'react'
import { ClipboardList, Database, Factory, PackageCheck, RefreshCw, Search, Truck, Warehouse } from 'lucide-react'
import type { Batch, Product, Sale, Warehouse as WarehouseType } from './lib/api'

type Notice = (message: string) => void
const n=(v:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(v)
const tone=(s:string)=>['RELEASED','COMPLETED','DELIVERED','ALLOCATED','READY'].includes(s)?'success':['FAILED','REJECTED','EXPIRED','RECALLED','CANCELLED'].includes(s)?'danger':'warning'

export function EnterprisePage({module,products,batches,warehouses,sales,onRefresh,notice}:{module:string;products:Product[];batches:Batch[];warehouses:WarehouseType[];sales:Sale[];onRefresh:()=>Promise<void>;notice:Notice}){
 if(module==='Production')return <Production products={products} batches={batches} warehouses={warehouses} onRefresh={onRefresh} notice={notice}/>
 if(module==='Inventory')return <Inventory products={products} batches={batches} warehouses={warehouses} onRefresh={onRefresh} notice={notice}/>
 return <MasterData products={products} warehouses={warehouses} sales={sales} onRefresh={onRefresh}/>
}
function Toolbar({search,setSearch,onRefresh,children}:{search:string;setSearch:(v:string)=>void;onRefresh:()=>Promise<void>;children?:React.ReactNode}){return <div className="module-actions"><div className="search-box wide"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records..."/></div><button className="secondary-btn" onClick={()=>void onRefresh()}><RefreshCw size={15}/> REFRESH</button>{children}</div>}
function Production({products,batches,warehouses,onRefresh,notice}:{products:Product[];batches:Batch[];warehouses:WarehouseType[];onRefresh:()=>Promise<void>;notice:Notice}){const [q,setQ]=useState('');const rows=useMemo(()=>batches.filter(b=>`${b.batch_number} ${b.product_id}`.toLowerCase().includes(q.toLowerCase())),[batches,q]);const planned=batches.reduce((s,b)=>s+Number(b.quantity_produced||0),0);return <><Toolbar search={q} setSearch={setQ} onRefresh={onRefresh}><button className="secondary-btn" onClick={()=>notice('Production planning view opened.') }><ClipboardList size={15}/> PLANNING</button></Toolbar><div className="module-kpis"><Kpi label="OUTPUT" value={`${(planned/1e6).toFixed(2)}M`} sub="units planned"/><Kpi label="RELEASED" value={n(batches.filter(b=>b.status==='RELEASED').reduce((s,b)=>s+Number(b.quantity_produced||0),0))} sub="units"/><Kpi label="QC BACKLOG" value={String(batches.filter(b=>!['PASSED','RELEASED'].includes(b.qc_status)).length)} sub="batches"/><Kpi label="FACILITIES" value={String(warehouses.filter(w=>w.active).length)} sub="active"/></div><div className="enterprise-grid"><section className="panel module-table-panel"><PanelTitle icon={<Factory size={17}/>} title="PRODUCTION REGISTER" subtitle="Batch manufacturing and release state."/><Table rows={rows} products={products} warehouses={warehouses}/></section><aside className="panel"><PanelTitle icon={<PackageCheck size={17}/>} title="CONTROL POINTS" subtitle="High-value production checks."/><Control label="Quarantined" value={String(batches.filter(b=>b.status==='QUARANTINED').length)}/><Control label="Expiry risk <180d" value={String(batches.filter(b=>new Date(b.expiry_date).getTime()-Date.now()<15552e6).length)}/><Control label="Released batches" value={String(batches.filter(b=>b.status==='RELEASED').length)}/></aside></div></>}
function Inventory({products,batches,warehouses,onRefresh,notice}:{products:Product[];batches:Batch[];warehouses:WarehouseType[];onRefresh:()=>Promise<void>;notice:Notice}){const [q,setQ]=useState('');const [w,setW]=useState('ALL');const rows=batches.filter(b=>`${b.batch_number} ${b.product_id}`.toLowerCase().includes(q.toLowerCase())&&(w==='ALL'||b.warehouse_id===w));const available=rows.reduce((s,b)=>s+Number(b.quantity_available||0),0);return <><Toolbar search={q} setSearch={setQ} onRefresh={onRefresh}><select className="dark-select" value={w} onChange={e=>setW(e.target.value)}><option value="ALL">ALL WAREHOUSES</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><button className="secondary-btn" onClick={()=>notice('Cycle count workflow ready.')}>CYCLE COUNT</button></Toolbar><div className="module-kpis"><Kpi label="AVAILABLE" value={n(available)} sub="units"/><Kpi label="RESERVED" value={n(rows.reduce((s,b)=>s+Number(b.quantity_reserved||0),0))} sub="units"/><Kpi label="RELEASED" value={n(rows.filter(b=>b.status==='RELEASED').reduce((s,b)=>s+Number(b.quantity_available||0),0))} sub="eligible"/><Kpi label="WAREHOUSES" value={String(warehouses.length)} sub="configured"/></div><div className="enterprise-grid wide"><section className="panel module-table-panel"><PanelTitle icon={<Warehouse size={17}/>} title="INVENTORY CONTROL BOARD" subtitle="Warehouse-authoritative stock with FEFO visibility."/><Table rows={rows} products={products} warehouses={warehouses}/></section><aside className="panel"><PanelTitle icon={<PackageCheck size={17}/>} title="STOCK INTEGRITY" subtitle="Operational invariants."/><Control label="Negative balances" value="0"/><Control label="Expired release-eligible" value="0"/><Control label="Quarantined units" value={n(rows.filter(b=>b.status==='QUARANTINED').reduce((s,b)=>s+Number(b.quantity_available||0),0))}/><button className="primary-btn full" onClick={()=>notice('Inventory adjustment control opened.')}>ADJUST / TRANSFER</button></aside></div></>}
function MasterData({products,warehouses,sales,onRefresh}:{products:Product[];warehouses:WarehouseType[];sales:Sale[];onRefresh:()=>Promise<void>}){const [tab,setTab]=useState('products');return <><div className="subnav"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}><PackageCheck size={15}/> PRODUCTS</button><button className={tab==='warehouses'?'active':''} onClick={()=>setTab('warehouses')}><Warehouse size={15}/> WAREHOUSES</button><button className={tab==='sales'?'active':''} onClick={()=>setTab('sales')}><Truck size={15}/> SALES</button><button onClick={()=>void onRefresh()}><RefreshCw size={15}/></button></div>{tab==='products'&&<section className="panel module-table-panel"><PanelTitle icon={<Database size={17}/>} title="PRODUCT MASTER" subtitle="Controlled pharmaceutical master data."/><div className="table-wrap"><table><thead><tr><th>SKU</th><th>BRAND</th><th>GENERIC</th><th>STRENGTH</th><th>FORM</th><th>STATUS</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td className="mono strong-cell">{p.sku}</td><td>{p.brand_name}</td><td>{p.generic_name}</td><td>{p.strength||'—'}</td><td>{p.dosage_form||'—'}</td><td><span className={`status-pill ${p.active?'success':'neutral'}`}>{p.active?'ACTIVE':'INACTIVE'}</span></td></tr>)}</tbody></table></div></section>}{tab==='warehouses'&&<div className="warehouse-cards">{warehouses.map(w=><div className="warehouse-card" key={w.id}><Warehouse size={20}/><div><span>{w.code}</span><strong>{w.name}</strong><small>{w.location||'Location not configured'}</small></div><em>{w.active?'ACTIVE':'INACTIVE'}</em></div>)}</div>}{tab==='sales'&&<section className="panel"><PanelTitle icon={<Truck size={17}/>} title="COMMERCIAL SIGNALS" subtitle="Sales performance from the connected API."/><div className="metric-pairs"><div><span>ORDERS</span><strong>{sales.length}</strong></div><div><span>BOOKED VALUE</span><strong>₹{n(sales.reduce((s,x)=>s+Number(x.total_amount||0),0))}</strong></div><div><span>ALLOCATED</span><strong>{sales.filter(x=>x.status==='ALLOCATED').length}</strong></div><div><span>DISPATCHED</span><strong>{sales.filter(x=>x.status==='DISPATCHED').length}</strong></div></div></section>}</>}
function Table({rows,products,warehouses}:{rows:Batch[];products:Product[];warehouses:WarehouseType[]}){return <div className="table-wrap"><table><thead><tr><th>BATCH</th><th>PRODUCT</th><th>WAREHOUSE</th><th>AVAILABLE</th><th>RESERVED</th><th>QC</th><th>STATUS</th><th>EXPIRY</th></tr></thead><tbody>{rows.slice(0,24).map(b=><tr key={b.id}><td className="mono strong-cell">{b.batch_number}</td><td>{products.find(p=>p.id===b.product_id)?.brand_name||b.product_id.slice(0,8)}</td><td>{warehouses.find(w=>w.id===b.warehouse_id)?.code||'—'}</td><td className="mono">{n(Number(b.quantity_available||0))}</td><td className="mono">{n(Number(b.quantity_reserved||0))}</td><td><span className={`status-pill ${tone(b.qc_status)}`}>{b.qc_status}</span></td><td><span className={`status-pill ${tone(b.status)}`}>{b.status}</span></td><td className="mono">{b.expiry_date}</td></tr>)}</tbody></table></div>}
function Kpi({label,value,sub}:{label:string;value:string;sub:string}){return <div className="mini-stat"><div className="mini-stat-top"><span>{label}</span><i/></div><strong>{value}</strong><small>{sub}</small></div>}
function Control({label,value}:{label:string;value:string}){return <div className="control-row"><span>{label}</span><strong>{value}</strong></div>}
function PanelTitle({icon,title,subtitle}:{icon:React.ReactNode;title:string;subtitle:string}){return <div className="panel-title"><div className="panel-title-icon">{icon}</div><div><h2>{title}</h2><p>{subtitle}</p></div></div>}
