import { useState, type FormEvent, type ReactNode } from 'react'
import { X } from 'lucide-react'
import { api, type Batch, type Product, type Warehouse } from './lib/api'

export function ProductionOrderModal({ products, warehouses, onClose, onDone }: { products: Product[]; warehouses: Warehouse[]; onClose: () => void; onDone: (message: string) => Promise<void> }) {
  const [form, setForm] = useState({ order_number: `PO-${Date.now().toString().slice(-8)}`, product_id: products[0]?.id ?? '', warehouse_id: warehouses[0]?.id ?? '', planned_quantity: '10000', notes: '' })
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await api.createProduction({ ...form, planned_quantity: Number(form.planned_quantity) }); await onDone('Production order created successfully.') } catch (error) { await onDone(error instanceof Error ? error.message : 'Production order creation failed') } }
  return <Modal title="CREATE PRODUCTION ORDER" onClose={onClose}><form className="form-grid" onSubmit={submit}><Field label="ORDER NUMBER"><input required value={form.order_number} onChange={e => setForm({ ...form, order_number: e.target.value })} /></Field><Field label="PRODUCT"><select required value={form.product_id} onChange={e => setForm({ ...form, product_id: e.target.value })}>{products.map(product => <option key={product.id} value={product.id}>{product.brand_name} {product.strength ?? ''}</option>)}</select></Field><Field label="WAREHOUSE"><select value={form.warehouse_id} onChange={e => setForm({ ...form, warehouse_id: e.target.value })}>{warehouses.map(warehouse => <option key={warehouse.id} value={warehouse.id}>{warehouse.code} — {warehouse.name}</option>)}</select></Field><Field label="PLANNED QUANTITY"><input type="number" min="1" required value={form.planned_quantity} onChange={e => setForm({ ...form, planned_quantity: e.target.value })} /></Field><Field label="NOTES"><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field><Actions onClose={onClose} /></form></Modal>
}

export function TransferModal({ products, batches, warehouses, onClose, onDone }: { products: Product[]; batches: Batch[]; warehouses: Warehouse[]; onClose: () => void; onDone: (message: string) => Promise<void> }) {
  const [form, setForm] = useState({ product_id: products[0]?.id ?? '', batch_id: batches[0]?.id ?? '', from_warehouse_id: warehouses[0]?.id ?? '', to_warehouse_id: warehouses[1]?.id ?? warehouses[0]?.id ?? '', quantity: '100', reason: 'Operational transfer' })
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await api.transferStock({ ...form, quantity: Number(form.quantity) }); await onDone('Stock transfer completed atomically.') } catch (error) { await onDone(error instanceof Error ? error.message : 'Stock transfer failed') } }
  return <Modal title="TRANSFER STOCK" onClose={onClose}><form className="form-grid" onSubmit={submit}><Field label="PRODUCT"><select required value={form.product_id} onChange={e => setForm({ ...form, product_id: e.target.value })}>{products.map(product => <option key={product.id} value={product.id}>{product.brand_name} {product.strength ?? ''}</option>)}</select></Field><Field label="BATCH"><select required value={form.batch_id} onChange={e => setForm({ ...form, batch_id: e.target.value })}>{batches.map(batch => <option key={batch.id} value={batch.id}>{batch.batch_number}</option>)}</select></Field><Field label="FROM WAREHOUSE"><select required value={form.from_warehouse_id} onChange={e => setForm({ ...form, from_warehouse_id: e.target.value })}>{warehouses.map(warehouse => <option key={warehouse.id} value={warehouse.id}>{warehouse.code} — {warehouse.name}</option>)}</select></Field><Field label="TO WAREHOUSE"><select required value={form.to_warehouse_id} onChange={e => setForm({ ...form, to_warehouse_id: e.target.value })}>{warehouses.map(warehouse => <option key={warehouse.id} value={warehouse.id}>{warehouse.code} — {warehouse.name}</option>)}</select></Field><Field label="QUANTITY"><input required type="number" min="1" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></Field><Field label="REASON"><textarea value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></Field><Actions onClose={onClose} /></form></Modal>
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span>PHARMACORE CONTROL</span><h2>{title}</h2></div><button className="icon-btn" onClick={onClose}><X size={18} /></button></div>{children}</div></div> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Actions({ onClose }: { onClose: () => void }) { return <div className="modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>CANCEL</button><button className="primary-btn">SAVE / SUBMIT</button></div> }
